# Default values for webproject.

projectname: developer-cthorn
projectdomainname: developer-cthorn.kube.domain.tld
projectmainbranch: master

# Name of secret that contains aws s3 bucket info
aws:
  enabled: true
  secretname: secretname

# Ingress hosts
ingresshosts:
  - domainone
  - domaintwo
  - domainthree

webcontainer:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "1.19.4"

# Sidecars containers

# CLI container for the webcontainer.
clisidecar:
  enabled: true
  repository: outrigger/cli
  pullPolicy: IfNotPresent
  tag: "2-php7.3"

# Database container for the webcontainer. Can be mysql or mariadb.
# We recommend using a specific tag
databasesidecar:
  enabled: true
  repository: mariadb
  pullPolicy: IfNotPresent
  tag: "10.5"
  dbinfo:
    databasename: developer_cthorn_db
    databaseuser: admin
    databaseuserpassword: "admin123#"
    databasestoragesize: 5Gi
    databasestoragemountpath: /var/lib/mysql
    databaserootpassword: "412qwepdS"

# Cache container for the webcontainer. Can be redis or memcached.
cachesidecar:
  enabled: true
  repository:  redis
  pullPolicy: IfNotPresent
  tag: "6.0.9-alpine"
  port: 6379

# File storege size and mountpath
filestoragesize: 10Gi
filestoragemountpath: /var/www/html/sites/default/files

# docker config information
dockerconfig:
  username: dockeruserename
  password: dockeruserpassword
  email: dockerusername@domain.tld
  registryurl: registry.domain.tld

# Use CSI Volumes for volumesnapshots.
# The workload created from the release-projectmainbranch will be the source
# of the volumesnapshot
# The snapshotsource if left as default will use the workload derived from the projectmainbranch
# otherwise it could be issue-1234-testing
# snapshotsource: default
#csivolumes:
#   enabled: false
#   storageclass: standard-one
#   snapshots:
#     database:
#       enabled: false
#       snapshotsource: default
#     files:
#       enabled: false
#       snapshotsource: default

# Project search workload.
#search:
#  solr:
#    enabled: true
#    repository:  solr
#    pullPolicy: IfNotPresent
#    tag: "8.0"
#    port: 8983
