---
apiVersion: wp.webproject-operator.io/v1alpha1
kind: WebProject
metadata:
  name: developer-cthorn-webproject
  labels:
    app.kubernetes.io/name: webproject
    app.kubernetes.io/instance: developer-cthorn
spec:
  # Project information
  projectname: developer-cthorn
  projectdomainname: developer-cthorn.kube.domain.tld

  deploymentannotations:
    "project-lead": "developer-name"
    "project-lead-email": "developer-name@domain.tld"
    "project-language": "lang"
  
  # AWS secret name

  # RELEASE_NAME
  releasename: developer-cthorn

  # default web image
  # nginx:1.19.4
  # httpd:2.4.46-alpine
  # php:7.4.14-apache-buster
  webcontainer:
    image: php:8.0.1-apache-buster
    cronjob:
      enabled: false
      schedule: "0 * * * *"
      script: |-
        #!/bin/bash
        echo "webcontainer cronjob script"

  # Sidecar Containers

  # cli sidecar image
  clisidecar:
    enabled: true
    image: outrigger/cli:2-php7.3

  # Search sidecar [solr or elasticsearch]
  # solr:8.7.0
  # elasticsearch:7.10.1
  # Drupal elasticsearch setup: composer require drupal/search_api drupal/elasticsearch_connector
  #  https://opensenselabs.com/blog/tech/use-elastic-search-indexing-drupal
  #  config-path: admin/config/search/elasticsearch-connector
  #  serverUrl: SEARCH_HOST (localhost:9200)
  searchsidecar:
    enabled: true
    # es|solr
    engine: es
    # image: solr:8.7.0
    image: elasticsearch:7.10.1
    cronjob:
      enabled: false
      schedule: "0 * * * *"
      script: |-
        #!/bin/bash
        echo "searchsidecar cronjob script"

  # database sidecar image
  # mysql:5.6.51
  # mariadb:10.5.8
  databasesidecar:
    enabled: true
    databasename: drupal_db
    databaseimage: mysql:5.6.51
    databaseuser: admin
    databaseuserpassword: admin123
    databasestoragesize: 2Gi
    databaserootpassword: rootpasswd123
    databasestoragemountpath: /var/lib/mysql
    cronjob:
      enabled: false
      schedule: "0 * * * *"
      script: |-
        #!/bin/bash
        echo "databasesidecar cronjob script"
    # Perform backups to aws or gcp bucket
    backup:
      enabled: false
      # aws, gcp
      provider: aws

      # aws: s3://
      # gcp: gs://
      bucket: s3://pahtobucket/dir/path/filename-[releasename]-latest.tar.gz

      # Add the following variable environment to a secret
      # aws
      # AWS_ACCESS_KEY_ID: #
      # AWS_SECRET_ACCESS_KEY: #
      # AWS_REGION: us-east-1
      # gcp
      # GCS_SERVICE_ACCOUNT_JSON_KEY: ?
      # GCS_PROJECT_ID: ?
      backupsecretname: backup-secret
      backupschedule: "0 * * * *"
      backupscheduledjobshistorylimit: 10


  # cache sidecar image
  # memcached:1.6.9
  # redis
  cachesidecar:
    enabled: true
    # cache engine: memcached or redis
    engine: memcached
    image: memcached:1.6.9

  # file storege size and mountpath
  filestoragesize: 10Gi
  filestoragemountpath: /var/www/html/sites/default/files

  # docker config information
  dockerconfig:
    enabled: true
    secretname: dockersecret

  # Ingress domains
  ingresshosts:
    - domainone
    - domaintwo
    - domainthree
    - domainfour
    - domainfive
    - domainsix
    - domainseven
    - domaineight
    - domainnine
    - domainten

  # Allow webapp to handle ssl redirects - nginx.ingress.kubernetes.io/ssl-redirect: "false"
  # Add auth - nginx.ingress.kubernetes.io/auth-url: https://auth.domain.com/prod/auth
  # Add signin - nginx.ingress.kubernetes.io/auth-signin: https://auth.domain.com/prod/signin
  # Add support for rewriting of target - "nginx.ingress.kubernetes.io/rewrite-target":    "/$2",
  # Add nginx.ingress.kubernetes.io/auth-tls-verify-client: "off" and nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  # if the project is using custom certs. (i.e. gatsby)
  ingressannotations:
    "kubernetes.io/ingress.class": "nginx"
    "nginx.ingress.kubernetes.io/proxy-body-size": "0"
    "nginx.ingress.kubernetes.io/proxy-buffer-size": "16k"
    "nginx.ingress.kubernetes.io/ssl-passthrough": "true"

  # initcontainer script
  initcontainerscript: |-
    #!/bin/bash
    # Hello cthorn
    set +x;
    #export $(cat /aws/env | xargs);
    set -x;
    date;
    #aws s3 cp ${AWS_BUCKET}sites/${RELEASE_NAME}.tgz site.tgz;
    date;
    #tar -xzf site.tgz -C /data;
    date;
    #rm -rf site.tgz

  # common configmap
  # required
  commonconfig:
   "BUILD_ID": "1234567890"
   "DOCROOT": "/var/www/docroot"
   "PROJECT_ENV": "project"
   "CI": "true"
   "PHP_MAX_EXECUTION_TIME": "30"
   "DBNAME": "databasename"
   "DBUSER": "databaseuser"
   "PHP_MEMORY_LIMIT": "512M"