apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: webprojects.wp.webproject-operator.io
spec:
  group: wp.webproject-operator.io
  names:
    kind: WebProject
    listKind: WebProjectList
    plural: webprojects
    singular: webproject
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: WebProject is the Schema for the webprojects API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: WebProjectSpec defines the desired state of WebProject
          properties:
            awsSecretName:
              type: string
            backup:
              description: WebProjectBackup defined the spec for backups.
              properties:
                backupSchedule:
                  type: string
                backupScheduledJobsHistorylimit:
                  type: integer
                enabled:
                  type: boolean
                storageProvider:
                  type: string
              required:
              - backupSchedule
              type: object
            cacheSidecar:
              description: WebProjectCacheSidecar defines spec for cache sidecar
              properties:
                cronJob:
                  description: WebProjectCronJob defines setup for cronjobs.
                  properties:
                    enabled:
                      type: boolean
                    schedule:
                      type: string
                    script:
                      type: string
                  required:
                  - enabled
                  - schedule
                  - script
                  type: object
                enabled:
                  type: boolean
                engine:
                  type: string
                image:
                  type: string
                redisPassword:
                  type: string
              required:
              - enabled
              type: object
            cliSidecar:
              description: WebProjectCLISidecar defines spec for cache sidecar
              properties:
                enabled:
                  type: boolean
                image:
                  type: string
                port:
                  format: int32
                  type: integer
              required:
              - enabled
              type: object
            commonConfig:
              additionalProperties:
                type: string
              type: object
            databaseSidecar:
              description: WebProjectDatabaseSidecar defines the desired state for
                database sidecar
              properties:
                backup:
                  description: WebProjectBackup defined the spec for backups.
                  properties:
                    backupSchedule:
                      type: string
                    backupScheduledJobsHistorylimit:
                      type: integer
                    enabled:
                      type: boolean
                    storageProvider:
                      type: string
                  required:
                  - backupSchedule
                  type: object
                cronJob:
                  description: WebProjectCronJob defines setup for cronjobs.
                  properties:
                    enabled:
                      type: boolean
                    schedule:
                      type: string
                    script:
                      type: string
                  required:
                  - enabled
                  - schedule
                  - script
                  type: object
                databaseImage:
                  type: string
                databaseName:
                  type: string
                databaseRootPassword:
                  type: string
                databaseStorageMountPath:
                  type: string
                databaseStorageSize:
                  type: string
                databaseUser:
                  type: string
                databaseUserPassword:
                  type: string
                enabled:
                  type: boolean
              type: object
            deploymentAnnotations:
              additionalProperties:
                type: string
              type: object
            fileStorageMountPath:
              type: string
            fileStorageSize:
              type: string
            imagePullSecrets:
              description: WebProjectDockerConfig defines setup ImagePullSecret for
                private registry.
              properties:
                enabled:
                  type: boolean
                secretName:
                  type: string
              required:
              - enabled
              type: object
            ingressAnnotations:
              additionalProperties:
                type: string
              type: object
            ingressHosts:
              items:
                type: string
              type: array
            initContainerScript:
              type: string
            projectDomainName:
              type: string
            projectName:
              type: string
            releaseName:
              type: string
            searchSidecar:
              description: WebProjectSearchSidecar defines spec for cache sidecar
              properties:
                cronJob:
                  description: WebProjectCronJob defines setup for cronjobs.
                  properties:
                    enabled:
                      type: boolean
                    schedule:
                      type: string
                    script:
                      type: string
                  required:
                  - enabled
                  - schedule
                  - script
                  type: object
                enabled:
                  type: boolean
                engine:
                  type: string
                image:
                  type: string
              required:
              - enabled
              type: object
            webContainer:
              description: WebProjectWebContainer defines to spec for webcontainer
              properties:
                cronJob:
                  description: WebProjectCronJob defines setup for cronjobs.
                  properties:
                    enabled:
                      type: boolean
                    schedule:
                      type: string
                    script:
                      type: string
                  required:
                  - enabled
                  - schedule
                  - script
                  type: object
                image:
                  type: string
              required:
              - image
              type: object
          required:
          - commonConfig
          - fileStorageMountPath
          - fileStorageSize
          - projectDomainName
          - projectName
          - releaseName
          - webContainer
          type: object
        status:
          description: WebProjectStatus defines the observed state of WebProject
          properties:
            configMapNames:
              items:
                type: string
              type: array
            cronJobNames:
              items:
                type: string
              type: array
            deploymentNames:
              items:
                type: string
              type: array
            podNames:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html
                WebProject WebProjectSpec `json:"webproject,omitempty"`'
              items:
                type: string
              type: array
            secretNames:
              items:
                type: string
              type: array
          required:
          - configMapNames
          - cronJobNames
          - deploymentNames
          - podNames
          - secretNames
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
