apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: webprojects.wp.webproject-operator.io
spec:
  group: wp.webproject-operator.io
  names:
    kind: WebProject
    listKind: WebProjectList
    plural: webprojects
    singular: webproject
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: WebProject is the Schema for the webprojects API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: WebProjectSpec defines the desired state of WebProject
          properties:
            awssecretname:
              type: string
            backup:
              description: WebProjectBackup defined the spec for backups.
              properties:
                backupschedule:
                  type: string
                enabled:
                  type: boolean
                storageprovider:
                  type: string
              required:
              - backupschedule
              type: object
            cachesidecar:
              description: WebProjectCacheSidecar defines spec for cache sidecar
              properties:
                cronjob:
                  description: WebProjectCronJob defines setup for cronjobs.
                  properties:
                    enabled:
                      type: boolean
                    schedule:
                      type: string
                    script:
                      type: string
                  required:
                  - enabled
                  - schedule
                  - script
                  type: object
                enabled:
                  type: boolean
                engine:
                  type: string
                image:
                  type: string
              required:
              - enabled
              type: object
            clisidecar:
              description: WebProjectCLISidecar defines spec for cache sidecar
              properties:
                enabled:
                  type: boolean
                image:
                  type: string
                port:
                  format: int32
                  type: integer
              required:
              - enabled
              type: object
            commonconfig:
              additionalProperties:
                type: string
              type: object
            databasesidecar:
              description: WebProjectDatabaseSidecar defines the desired state for
                database sidecar
              properties:
                backup:
                  description: WebProjectBackup defined the spec for backups.
                  properties:
                    backupschedule:
                      type: string
                    enabled:
                      type: boolean
                    storageprovider:
                      type: string
                  required:
                  - backupschedule
                  type: object
                cronjob:
                  description: WebProjectCronJob defines setup for cronjobs.
                  properties:
                    enabled:
                      type: boolean
                    schedule:
                      type: string
                    script:
                      type: string
                  required:
                  - enabled
                  - schedule
                  - script
                  type: object
                databaseimage:
                  type: string
                databasename:
                  type: string
                databaserootpassword:
                  type: string
                databasestoragemountpath:
                  type: string
                databasestoragesize:
                  type: string
                databaseuser:
                  type: string
                databaseuserpassword:
                  type: string
                enabled:
                  type: boolean
              type: object
            deploymentannotations:
              additionalProperties:
                type: string
              type: object
            dockerconfig:
              description: WebProjectDockerConfig defines setup ImagePullSecret for
                private registry.
              properties:
                enabled:
                  type: boolean
                secretname:
                  type: string
              required:
              - enabled
              type: object
            filestoragemountpath:
              type: string
            filestoragesize:
              type: string
            ingressannotations:
              additionalProperties:
                type: string
              type: object
            ingresshosts:
              items:
                type: string
              type: array
            initcontainerscript:
              type: string
            projectdomainname:
              type: string
            projectname:
              type: string
            releasename:
              type: string
            searchsidecar:
              description: WebProjectSearchSidecar defines spec for cache sidecar
              properties:
                enabled:
                  type: boolean
                engine:
                  type: string
                image:
                  type: string
              required:
              - enabled
              type: object
            webcontainer:
              description: WebProjectWebContainer defines to spec for webcontainer
              properties:
                cronjob:
                  description: WebProjectCronJob defines setup for cronjobs.
                  properties:
                    enabled:
                      type: boolean
                    schedule:
                      type: string
                    script:
                      type: string
                  required:
                  - enabled
                  - schedule
                  - script
                  type: object
                image:
                  type: string
              required:
              - image
              type: object
          required:
          - commonconfig
          - filestoragemountpath
          - filestoragesize
          - projectdomainname
          - projectname
          - releasename
          - webcontainer
          type: object
        status:
          description: WebProjectStatus defines the observed state of WebProject
          properties:
            configmapNames:
              items:
                type: string
              type: array
            podNames:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html
                WebProject WebProjectSpec `json:"webproject,omitempty"`'
              items:
                type: string
              type: array
            secretNames:
              items:
                type: string
              type: array
          required:
          - configmapNames
          - podNames
          - secretNames
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
