apiVersion: apps/v1
kind: Deployment
metadata:
  name: webproject-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: webproject-operator
  template:
    metadata:
      labels:
        name: webproject-operator
    spec:
      serviceAccountName: webproject-operator
      containers:
        - name: webproject-operator
          # Replace this with the built image name
          image: chaunceyt/webproject-operator:v0.0.1
          command:
          - webproject-operator
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "webproject-operator"
