{{- $namespace := .Values.namespace.name -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webproject-operator.fullname" . }}
  namespace: {{ $namespace  }}
  labels:
    {{- include "webproject-operator.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: webproject-operator
  template:
    metadata:
      labels:
        name: webproject-operator
    spec:
      serviceAccountName: {{ include "webproject-operator.fullname" . }}
      containers:
        - name: webproject-operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command:
          - webproject-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "webproject-operator"
